### ISSUE TITLE
Scripts not running after the last utils.sh

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#193]
./Zenroom/test/zencode_array/run.sh

./Zenroom/test/zencode_cookbook/run-dictionaries.sh

./Zenroom/test/zencode_cookbook/benchmark-50xECDSA-sign.sh

./Zenroom/test/zencode_dp3t/dp3t_vectors.sh    (needs run.sh in adavance) 

/Zenroom/test/zencode_ecdh  (all broken, except run.sh) 

./Zenroom/test/zencode_given/run.sh

./Zenroom/test/zencode_w3c/run.sh

**Comment by jaromil** [comment]
The script `./Zenroom/test/zencode_dp3t/dp3t_vectors.sh` just needs to be run from the root of the zenroom project:

```
./test/zencode_dp3t/dp3t_vectors.sh
```
after building. This is different because not a test, referenced in [this blog article](https://medium.com/think-do-tank/decentralized-privacy-preserving-proximity-tracing-cryptography-made-easy-af0a6ae48640)

can be left as-is
