### ISSUE TITLE
New zencode_parse/validate calls

### ISSUE THREAD

**Issue by jaromil** [dyne/Zenroom#227]
More than one use-case has highlighted the need for a call that can parse the syntax of a zencode script and return if valid.

This also opens the possibility for another call that can parse the syntax and execute the Given statements to return if input is valid as expected.

The solution is to implement two new calls available from zenroom header and bindings:
```c
// parse script and return if valid for syntax parser (no execution)
int zencode_parse_tobuf(char *script, char *stderr_buf, size_t stderr_len);

// parse script and execute Given steps to indicate if syntax valid and input valid
int zencode_validate_tobuf(char *script, char *conf, char *keys, char *data,
                                            char *stdout_buf, size_t stdout_len,
                                            char *stderr_buf, size_t stderr_len);
```
Both calls should return JSON parsable output since their use is in programmatic environment as libs.

**Comment by matteo-cristino** [comment]
I think the time for these apis has come. In [@slangroom/ignored](https://github.com/dyne/slangroom/blob/main/pkg/ignored/src/index.ts) we are executing the contract followed by a regex to see what statements have been ignored by zenroom (when rule unknown ignore is present). This approach is not good since if we modify the warning message from zenroom then we will have to remember to modify it also from slangroom.

Thus an api that return ignored statements and invalid lines will fit perfectly there.

**Comment by matteo-cristino** [comment]
Possibly the line number should also be reutrned with the ignored or not valid statment
