### ISSUE TITLE
 Internal memory error: missing CODEC 

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#470]
Script:

```
Given I have a 'string dictionary' named 'peppe'

Then print the data from 'peppe'
Then print the 'peppe'
```

Data:

```
{
	"peppe": {
		"bitcoin": "L2werKzNCkBK1DFjmsMuJPN28JC4cXWdEFZzGEz5ZTUDPitF88Vu",
		"ecdh": "IH0QgLdzFVoBu0JCbuUc5H7d3YIHGDNoaNqUc4YWVY0=",
		"eddsa": "285BLeXC2fMvrm3HKucer5rLn2PvfHRpDxQw6R7MX2DE",
		"ethereum": "78d427f1f3cf5e32d5f8971d546bd2d718697e66c0b6aa11b511c027a614798f",
		"reflow": "GklV6pSwm7xTod4JIq0g/6BsDrkofLeJCzEaq7eEgy8=",
		"schnorr": "XLD1zAeG6aqs2wOYM4XiwmvqjgPxMMLzsOkkVWuWZwM="
	}
}
```

Output:

1661518563759E[!] ERROR:
1661518563759E[!] EXEC: /zencode.lua:588: Internal memory error: missing CODEC for ethereum

**Comment by jaromil** [comment]
@andrea-dintino related to the coarse grained codec branch

**Comment by matteo-cristino** [comment]
I think that the problem is given by the following line of code
https://github.com/dyne/Zenroom/blob/1b0c48870a82e683b13d4fc06db10014eee482b3/src/lua/zencode_then.lua#L275
inside the statement
```
print data from ''
```
in which a new element is added to the ACK memory, but no codec is provided.
I can fix it next week if you want.
