### ISSUE TITLE
Then codec for integer/float/number is broken

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/Zenroom#627]
Code:

```
Given I have a 'integer' named 'i'
Given I have a 'float' named 'f'
Given I have a 'number' named 'n'

then print data as 'hex'
```

data:

```
{
	"i": "1680597100175",
	"n": "1680597100175",
	"f": "1680597100175"
}
```

Output: 

```
{
   "f": 1680597000000,
   "i": "1680597100175",
   "n": 1680597000000
}
```

**Comment by matteo-cristino** [comment]
For the [universal-registrar](https://github.com/decentralized-identity/universal-registrar) I would need to convert the private keys to base58, in particular the reflow key whose codec is an integer. Should I work on this issue to have this problem solved or there is any workaround that would let me do this?

**Comment by albertolerda** [comment]
I think that numbers, if printed with a decimal representation, are usually more user-friendly and easier to read. Still, I do understand that this leads to an exception that limits the functionality of zenroom.
What do you propose? I think that the easiest solution is to align BIG e FLOAT with the usual `:octet()` conversion and then we could build a statement "When I create the decimal string from ''`.

This means that by default numbers will be printed as base64, the user can decide to print a number as decimal using a specific statement.

Maybe we could keep the exception if a float, because in this case the :octet() is not really interesting (it is a representation of the ascii string)

**Comment by matteo-cristino** [comment]
I think we can still let the default export to decimal representation (if its encoding is `integer` for example), but if I use the statement `Then print the 'number' as 'encoding'` it should be able to transform it to the desired encoding. 
In my mind I see a similarity with the strings, the default is the string format, but I'm able to print them in all the encoding that I want.

**Comment by matteo-cristino** [comment]
Looking at the code, I see that one of the major problem is that the sign is not carried in the transformation from BIG to octet. Thus, as it is, all the BIGs will be postive once transformed to octet. How this should be managed? It make sense to add a new filed to the octet structure to carry the sign in the case of BIG?

**Comment by albertolerda** [comment]
No, not a field in the octet struct, at most a byte during the encoding of a big.
But then we would have to impose our own encoding of bigs and when we are provided an octet we cannot decode it directly to a positive number
