### ISSUE TITLE
Questions about C API usage

### ISSUE THREAD

**Issue by fdeantoni** [dyne/Zenroom#95]
First of all this is a very interesting project that nicely encapsulates the complexities of cryptography using a nice DSL. I'm experimenting with the C API as described [here](https://dev.zenroom.org/#/pages/how-to-embed), but have a few questions about its usage:

1. What is the difference between the parameter `keys` and `data`? When will the Zencode fail if keys data is passed into `data` instead of `keys` (or vice versa)?
2. Is there a way to suppress all printing to console by the library? Currently the following is printed when making calls to the API:
```
[*] Memory manager selected: lightweight
 .  ECDH curve is GOLDILOCKS
 .  Memory in use: 277 KB
```
3. Is there documentation somewhere about all the configuration options that can be passed? 
4. Does the return of the C API only return 0 for success and 1 for failure, or does it return additional error codes?

**Comment by jaromil** [comment]
hi there! 2. should be fixed now, addressing the rest:
1. Zencode will find anything in KEYS and DATA just the same. The difference is that Zenroom may use underlying OS techniques to protect KEYS from being accessed by external processes and in general doesn't forces the host developer to join public with private data exposing it to further risks.
2.  should be fixed in the latest build, please let me know
3. coming up soon, so far best reference is src/zen_config.c
4. the C API only returns 0 for success and 1 for failure, one should lookup stderr for reasons.

Thanks for your interest and good feedback !
